const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "docs", "index.html"), "utf8");
const cname = fs.readFileSync(path.join(root, "docs", "CNAME"), "utf8").trim();
const installer = fs.readFileSync(path.join(root, "docs", "install.sh"), "utf8");
const inlineScripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match => match[1]);

function check(condition, message) {
    if (!condition) throw new Error(message);
}

check(cname === "motd.foxly.de", "Unexpected CNAME");
check(html.includes("https://motd.foxly.de/install.sh"), "Install URL missing");
check(html.includes("foxly-it/foxly-motd"), "GitHub repository link missing");
check(html.includes('meta name="description"'), "Meta description missing");
check(html.includes('data-de='), "German website content missing");
check(html.includes('data-en='), "English website content missing");
check(html.includes('navigator.language'), "Automatic browser language selection missing");
check(html.includes("https://foxly.de/datenschutzerklaerung/"), "Privacy link missing");
check(html.includes("https://foxly.de/legal-notice/"), "Legal notice link missing");
check(html.includes('data-terminal="de"') && html.includes('data-terminal="en"'), "Bilingual terminal preview missing");
check((html.match(/class="rainbow"/g) || []).length === 2, "Rainbow HomeLab preview missing");
check(html.includes("/ /_/ / __ \\/ __ `__ \\/ _ \\/ /"), "HomeLab ASCII art missing");
check(html.includes("10.0.0.20/24") && html.includes("DNS-Server:"), "Network details missing from preview");
check(html.includes("Systemd-Dienste:") && html.includes("aktiv: 17") && !html.includes("fehlerhaft: 0"), "Health or filtered Docker details missing from preview");
check(html.includes("[ NETZWERK ]") && html.includes("[ RESSOURCEN ]") && html.includes("[ SITZUNG ]") && html.includes("[ SYSTEMSTATUS ]") && html.includes("[ PAKET-UPDATES ]"), "Three-column German dashboard preview missing");
check(html.includes("[ NETWORK ]") && html.includes("[ RESOURCES ]") && html.includes("[ SESSION ]") && html.includes("[ SYSTEM HEALTH ]"), "Grouped English dashboard preview missing");
check((html.match(/class="terminal-dashboard"/g) || []).length === 2 && (html.match(/class="terminal-dashboard secondary"/g) || []).length === 2, "Grid-based terminal dashboard missing");
check((html.match(/class="terminal-card"/g) || []).length === 12, "Terminal dashboard cards missing");
check((html.match(/class="terminal-icon"/g) || []).length === 12 && html.includes("row-gap:.16em") && html.includes("margin-bottom:.32em"), "Terminal icon sizing or vertical rhythm missing");
check(html.includes("🐳 Docker-Container") && html.includes("🐳 Docker containers") && html.includes('de?"aktiv:":"running:"'), "Framed Docker preview missing");
check(!html.includes("⚙ Systemd"), "Fragile system-health glyph remains in preview");
check((html.match(/class="sysinfo-box"/g) || []).length === 2, "Framed system information preview missing");
check(html.includes("width:min(1400px") && html.includes("minmax(320px,.7fr) minmax(0,1.3fr)"), "Wide terminal layout missing");
check(html.includes("function fitTerminalPreview") && html.includes("pre.scrollWidth>viewport.clientWidth"), "Rendered terminal-width fitting missing");
check(html.includes("function alignedDetails") && html.includes("function alignStaticTerminalCards") && html.includes("grid-template-columns:max-content max-content"), "Aligned terminal value tabs missing");
check(html.includes("@media(max-width:1100px)"), "Wide terminal breakpoint missing");
check(html.includes("@media(max-width:900px)") && html.includes("repeat(2,max-content)"), "Tablet terminal grid missing");
check(html.includes("@media(max-width:560px)") && html.includes("grid-template-columns:max-content;row-gap:1.35em"), "Smartphone terminal grid missing");
check(html.includes("function responsiveCardColumns") && html.includes("renderCardGrid(assistantCards(language),columns)"), "Responsive assistant columns missing");
check((html.match(/class="terminal-prompt"/g) || []).length === 2, "Terminal prompts missing");
check((html.match(/class="cursor" aria-hidden="true"/g) || []).length === 2, "Terminal cursors missing");
check(html.includes("@keyframes cursor-blink") && html.includes("prefers-reduced-motion:reduce"), "Accessible cursor animation missing");
check(html.includes("@keyframes terminal-settle") && html.includes("rotateY(-8deg) translateX(16px)"), "Terminal hover animation missing");
check(html.includes("(hover:hover) and (pointer:fine)"), "Terminal hover capability guard missing");
check(html.includes('id="configurator"') && html.includes('id="motd-configurator"'), "Visual configurator missing");
check(html.includes('id="project"') && html.includes('id="project-version"') && html.includes('id="project-downloads"'), "Live project statistics missing");
check((html.match(/class="activity-card"/g) || []).length === 3, "Three-column project activity grid missing");
check(html.includes("releases?per_page=100") && html.includes("commits?sha=main&per_page=1") && html.includes("pulls?state=closed"), "GitHub activity endpoints missing");
check(html.includes("download_count") && html.includes("sessionStorage") && html.includes("600000"), "Live download count or API cache missing");
check(html.includes("setProjectText") && html.includes("element.textContent=value") && !html.includes("activity-title\").innerHTML"), "External GitHub text is not rendered safely");
check(html.includes('id="assistant-preview"') && html.includes('aria-live="polite"'), "Accessible live preview missing");
check(html.includes('id="assistant-config"') && html.includes("copyAssistantConfig"), "Generated configuration output missing");
check(html.includes('id="cfg-frame"') && html.includes('id="cfg-package-names"') && html.includes('id="cfg-package-limit"'), "Appearance and package controls missing");
check(html.includes("SHOW_NETWORK=") && html.includes("SHOW_FRAME=") && html.includes("PACKAGE_NAME_LIMIT="), "Modular generated settings missing");
const widthHelpers = html.match(/function displayGraphemes[\s\S]*?(?=    function renderCardGrid)/);
check(widthHelpers, "Display-width helpers missing");
const widthChecks = new Function(`${widthHelpers[0]}; return [displayWidth("🌐 A"), displayWidth("⚙ A"), padDisplay("🌐", 4)];`)();
check(widthChecks[0] === 4 && widthChecks[1] === 3 && widthChecks[2] === "🌐  ", "Emoji-aware frame padding is incorrect");
check(html.includes('className="terminal-wide"') && html.includes("width:2ch"), "Fixed-width emoji rendering missing");
const fitHelper = html.match(/function fitTerminalPreview[\s\S]*?(?=    let fitRequest)/);
check(fitHelper, "Terminal fitting helper missing");
const fittedSize = new Function(`${fitHelper[0]}; let size; const pre={parentElement:{clientWidth:100},scrollWidth:130,style:{set fontSize(value){size=parseFloat(value);pre.scrollWidth=size*10}}}; fitTerminalPreview(pre); return size;`)();
check(fittedSize === 10, "Terminal fitting does not use the visible parent width");
const responsiveHelpers = html.match(/function responsiveCardColumns[\s\S]*?(?=    function renderAssistant)/);
check(responsiveHelpers, "Responsive assistant helpers missing");
const responsiveChecks = new Function(`const window={innerWidth:1200}; const padDisplay=(value,width)=>value.padEnd(width," "); ${responsiveHelpers[0]}; const preview=width=>({parentElement:{clientWidth:width}}); return [responsiveCardColumns(preview(390)),responsiveCardColumns(preview(768)),responsiveCardColumns(preview(1200)),renderCardGrid([{title:"A",lines:["1"]},{title:"B",lines:["2"]}],1).includes("")];`)();
check(responsiveChecks.join(",") === "1,2,3,true", "Responsive assistant breakpoints are incorrect");
const projectSummaryHelpers = html.match(/function firstMeaningfulLine[\s\S]*?(?=    function setProjectText)/);
check(projectSummaryHelpers, "Project activity summary helper missing");
const projectSummary = new Function(`${projectSummaryHelpers[0]}; return summarizeProjectActivity([{tag_name:"v2.0.0",name:"Release 2",body:"## Changes\\n* Improve website by @foxly-it in https://github.com/foxly-it/foxly-motd/pull/4",draft:false,prerelease:false,published_at:"2026-01-03",assets:[{name:"foxly.tar.gz",download_count:12},{name:"checksums.txt",download_count:99}]}],[{sha:"abcdef123",html_url:"https://example.test/commit",commit:{message:"Ship release\\n\\nDetails",author:{name:"Foxly",date:"2026-01-02"}}}],[{number:4,title:"Merged work",merged_at:"2026-01-01",html_url:"https://example.test/pr",user:{login:"foxly"}}]);`)();
check(projectSummary.version === "v2.0.0" && projectSummary.downloads === 12 && projectSummary.releases === 1, "Project release statistics are incorrect");
check(projectSummary.commit.title === "Ship release" && projectSummary.commit.sha === "abcdef1" && projectSummary.pull.number === 4, "Commit or PR activity summary is incorrect");
check(projectSummary.release.entries.length === 1 && projectSummary.release.entries[0].pr === "4" && projectSummary.release.entries[0].author === "foxly-it", "Release log entries are incorrect");
check(html.includes("Existing values in /etc/default/foxly-motd are retained"), "Configuration migration notice missing");
inlineScripts.forEach(script => new Function(script));
check(installer.includes("sha256sum"), "Bootstrap installer does not verify SHA-256");
check(!html.includes("http://"), "Insecure HTTP URL found");

console.log("Web checks passed.");
